language: go
go:
- tip
install:
- go get github.com/nexustix/boilerplate
- go get github.com/nxReplicator/nxReplicatorCommon
before_deploy:
- env GOOS=linux GOARCH=amd64 go build -o ${HOME}/dist/linux64/nxreplicator github.com/nxReplicator/nxreplicator
- env GOOS=windows GOARCH=amd64 go build -o ${HOME}/dist/windows64/nxreplicator.exe github.com/nxReplicator/nxreplicator
deploy:
  provider: releases
  api_key:
    secure: suaEZkqMosojeB0DUsFjdgKejAN2ZjtpJ5NssU0v79w99NIcib+ldVuUo5kh9y1GDhT3Ec+1ISOLvLKViov6PBxuYJ58kz409YW+0JWLlGSojaATjyFWuh0EVc8y4/LuJXXq9qDon1Q0q/ohog/+Lu8VQJFp12sQW+CXvffXTbUwXDhKddFM4dNtGZ7okATrESp0klaGyVsx/1nfhet9EXtPUbK4qZMhTAKy2qZVG8iCsX3Tyni2ppmmuTkXSEDcBpzDw5IGycolrgpZkJg+t0a0k+3yrcfvXyoaUyDAbpnVG6zW0WzHqcnFcmcRhZOQrXTjvHWnlgny73HUsQvyXII8iwKVj+LcPzlP3Z/nqUedY1lpYDrNKd1+AH0gA+aurEJOgnNzbj8FKtQF95Rur3TShzAu4JMVAlQ6C8OHI24VaiPT+7VftkTEBD9s9ttX6oHqjYVj+/RKdDG79tKvsuKd7ABsZTKU/6581zRkKRtVc5DXJu4Wn89cxfpK9dQeAmb3Og8R1BQU47S4vPxQA4gTZVr/UAYKqk7AwfDPdXOgaud6vQCSNF1Ve43v5rAXbFcK4iLL5RMn8zBx9vTdh28GeU5AyxxSQsOsA7QTyBW1NzpkDOBqyVx5sSGw6KFP3013mNP5rS9rTczn9SowCI+nbVnEEkcZjGQuwTl1kag=
  file:
    - "${HOME}/dist/windows64/nxreplicator.exe"
    - "${HOME}/dist/linux64/nxreplicator"
  skip_cleanup: true
  on:
    tags: true
